### ISSUE TITLE
CMORsnack: all variables, omission tracking, offline diag compatibility

### ISSUE THREAD

**Issue by ilaflott** [NOAA-GFDL/fre-cli#252]
this can be broken down into bits

~~- [ ] CMORsnack: offline diag compatibility ([link]())~~
~~- [ ] CMORsnack: omission tracking~~ pushing to the `cmorMEAL` step coming next
~~- [ ] CMORsnack: success across almost all, if not all, variables, including offline diags~~ changing this description a little bit.

- [x] success across many variables, including ones with GFDL-isms. 
#268 

- [x] `nc_copy` bug 
#250 

- [x] more flexible treatment of `lat`, `lon`, and their `_bnds`
#241 

- [x] netCDF file format handling- how? during `nc_copy` 
#238
